# Generated by Django 4.1.7 on 2025-01-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "DepartmentId",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("DepartmentName", models.CharField(max_length=200)),
                ("Budget", models.IntegerField()),
            ],
        ),
    ]
