# Generated by Django 4.1.7 on 2025-01-22 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Finance", "0001_initial"),
        ("HR", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="ManagerId",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="department",
                to="HR.staff",
            ),
        ),
    ]
