# Generated by Django 4.1.7 on 2025-01-22 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("HR", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "ProductId",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("ProductName", models.CharField(max_length=200)),
                ("Category", models.CharField(max_length=100)),
                ("Price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("StockLevel", models.IntegerField()),
                ("ReorderLevel", models.IntegerField()),
                ("LastPurchaseDate", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "StoreId",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("StoreName", models.CharField(max_length=200)),
                ("Location", models.CharField(max_length=200)),
                ("ContactNumber", models.CharField(max_length=15)),
                ("TotalSales", models.IntegerField()),
                ("OperatingHours", models.IntegerField()),
                (
                    "ManagerId",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="HR.staff",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockLocation",
            fields=[
                (
                    "StockLocationId",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("Quantity", models.IntegerField()),
                ("Date", models.DateTimeField(auto_now_add=True)),
                (
                    "ProductId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocklocation",
                        to="Inventory.product",
                    ),
                ),
                (
                    "StoreId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocklocation",
                        to="Inventory.store",
                    ),
                ),
            ],
        ),
    ]
