# Generated by Django 5.1.5 on 2025-01-31 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ReorderLevel',
            new_name='OrderLimit',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='ProductType',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='StockLevel',
            new_name='StockAmount',
        ),
        migrations.CreateModel(
            name='ProductLocation',
            fields=[
                ('ProductLocationId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Quantity', models.IntegerField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('ProductId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductLocation', to='Inventory.product')),
                ('StoreId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductLocation', to='Inventory.store')),
            ],
        ),
        migrations.DeleteModel(
            name='StockLocation',
        ),
    ]
