# Generated by Django 4.1.7 on 2025-01-22 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Finance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "StaffId",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("StaffName", models.CharField(max_length=200)),
                ("Role", models.CharField(max_length=200)),
                ("Salary", models.IntegerField()),
                ("HireDate", models.DateField(auto_now_add=True)),
                (
                    "DepartmentId",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff",
                        to="Finance.department",
                    ),
                ),
            ],
        ),
    ]
