# Generated by Django 5.1.5 on 2025-01-31 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='HireDate',
        ),
    ]
