# Generated by Django 5.1.5 on 2025-01-31 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Procurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='TotalAmount',
            new_name='FullCost',
        ),
    ]
