# Generated by Django 4.1.7 on 2025-01-22 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Inventory", "0001_initial"),
        ("HR", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sales",
            fields=[
                (
                    "SalesId",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("PaymentMethod", models.CharField(max_length=200)),
                ("TotalAmount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("DateOfSale", models.DateField(auto_now_add=True)),
                (
                    "ProductId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales",
                        to="Inventory.product",
                    ),
                ),
                (
                    "StaffId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales",
                        to="HR.staff",
                    ),
                ),
                (
                    "StoreId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="Inventory.store",
                    ),
                ),
            ],
        ),
    ]
